### ISSUE TITLE
Feature Request: There isn't a wiki

### ISSUE THREAD

**Issue by CoolCat467** [Grimmys/pygame_popup_manager#2]
I find this project interesting, and am looking into using it in a game I'm working on, but I noticed there isn't a wiki for it. Would it be possible to make one, or if not have the community make one? Thank you for your time. Have a nice day.

**Comment by Grimmys** [comment]
Hi,

Well I didn't make a wiki yet because I don't have any active users lol, I was thinking that [README.md](https://github.com/Grimmys/pygame_popup_manager/blob/main/README.md), [examples](https://github.com/Grimmys/pygame_popup_manager/tree/main/examples) and the possibility to contact me directly was sufficient.

Though it is a good idea, I could start something, you can share any idea you have about the structure that should have this wiki too!

**Comment by Grimmys** [comment]
Documentation is ongoing: https://pygame-popup-manager.readthedocs.io/en/latest/index.html

**Comment by CoolCat467** [comment]
Thank you for the update!

**Comment by Grimmys** [comment]
Closing this issue as documentation is pretty up-to-date with current status of the development
